import { ExperienceItem } from "@/types";

export const experiences: ExperienceItem[] = [
  {
    id: 1,
    type: "education",
    title: "Bacharelado em Engenharia de Software",
    institution: "Universiadade Federal do Ceara",
    period: "Ago 2026 - Presente",
    bullets: [],
    stack: [],
  },
  {
    id: 2,
    type: "work",
    title: "Desenvolvedor Full Stack — Freelancer",
    institution: "Autônomo",
    period: "Set 2024 – Presente",
    bullets: [
      "Construí sistemas de gestão de estoque e controle de vendas para peixarias, oficinas mecânicas e lojas de roupas, com frontend em React.js/Next.js e backend em Node.js integrado a PostgreSQL, gerenciando centenas de produtos por sistema, eliminando o controle via papel e reduzindo em até 32% o tempo operacional.",
      "Substituí o agendamento via WhatsApp por sistema próprio de agendamento online para barbearias, processando em média 21 agendamentos por semana e eliminando a troca manual de mensagens entre cliente e estabelecimento, utilizando Next.js,Tailwind CSS, Node.js e PostgreSQL.",
      "Conduzi o ciclo completo de projetos para 11 clientes, da prospecção e levantamento de requisitos in loco até dailys para alinhamento de progresso e prioridades, desenvolvimento, testes unitários em Vitest, documentação em Swagger e deploy containerizado com Docker, estruturando o código com Clean Architecture e DDD, resultando em sistemas que seguem ativos em produção com baixa necessidade de manutenção corretiva. ",
    ],
    stack: [
      "TypeScript",
      "Node.js",
      "Fastify",
      "Prisma",
      "PostgreSQL",
      "React",
      "Next.js",
      "Tailwind",
      "Docker",
    ],
  },
  {
    id: 3,
    type: "work",
    title: "Estagiário de Desenvolvimento Full Stack",
    institution: "Golden Cloud Technology",
    period: "Ago 2025 - Dez 2025",
    bullets: [
      "Identifiquei e corrigi em cerca de 2 dias uma vulnerabilidade crítica no fluxo de reset de senha, onde o token era retornado diretamente pela API, reestruturando o processo para envio exclusivo via SMTP, incluindo ajustes no front-end, e eliminando um risco real de exposição de dados dos usuários.",
      "Implementei 9 funcionalidades de um painel administrativo em Next.js, Tailwind CSS e ShadCN/UI, incluindo autenticação, dashboard dinâmico, gestão de usuários, filtros avançados e fluxos de cadastro com validação estruturada em Zod, participando de dailies para alinhamento com o time e contribuindo para a evolução do produto.",
      "Automatizei testes E2E em sistemas governamentais com Cypress e Gherkin (BDD), cobrindo fluxos críticos de cadastro e edição de dados e garantindo estabilidade das entregas em produção.",
    ],
    stack: [
      "TypeScript",
      "Next.js",
      "Tailwind",
      "ShadCN/UI",
      "Prisma",
      "Postman",
      "Cypress",
      "Gherkin BDD",
      "Git",
    ],
  },
  {
    id: 4,
    type: "education",
    title: "Técnico em Desenvolvimento de Sistemas",
    institution: "EEEP Jaime da Cunha Rebouças",
    period: "Fev 2022 – Dez 2025",
    bullets: [
      "Participei de competições de empreendedorismo desenvolvendo e gerenciando sistemas em equipe, com exposição a MVP, validação de ideias e gestão de projetos, chegando à etapa regional.",
      "Conquistei 2º lugar na Feira de Ciências com pesquisa sobre erosão costeira em Icapuí (CE), desenvolvendo também um artigo para o projeto.",
    ],
    stack: [
      "HTML",
      "CSS",
      "JavaScript",
      "Node.js",
      "MySQL",
      "Git",
      "MVP",
      "Gestao de Startups",
    ],
  },
];
